### ISSUE TITLE
关于官方原安卓dtb的整合

### ISSUE THREAD

**Issue by xdsnet** [lanseyujie/tn3399_v3#2]
首先感谢你的研究
因为我个人也搞了块这样的板子来折腾，所以有些问题想请教你一下：
1.如何提取官方的dtb，或者哪里可以直接下载到官方的dtb？我在你的编译脚本过程中没有找到相应处理。
2.如何整合官方的dtb到armbian？我在你的编译脚本和说明文档中没有具体的操作指导，希望能获得一下帮助。

谢谢！

**Comment by rossihwang** [comment]
我通过串口进入原android系统，将/proc/device-tree tar到u盘上。然后可以通过dtc将目录还原成dts或dtb，不过不能直接启动系统。有些字段应该是linux和android不一样的，比如chosen。你可以和论坛的dtb比较一下（我用的是wifi fix那个文件）。

**Comment by lanseyujie** [comment]
1. `/sys/firmware/fdt` 为原始 dtb，由于我备份的出厂镜像不完整尚不能完全恢复，暂时无法验证。
2. 对于论坛上的 [#60](https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=4033942&page=4#pid9538379) 楼帖子中提到的 Armbian 镜像整合 dtb，将镜像烧写在 SD 卡上，打开 boot 目录，使用该帖子中的 `rk3399-rock960.dtb` 或 [#98](https://www.right.com.cn/forum/forum.php?mod=redirect&goto=findpost&ptid=4033942&pid=9629530) 楼帖子中的 dtb 内容覆盖在 uEnv.txt 中指定的 `/dtb/rockchip/rk3399-nanopc-t4.dtb` 即可。

**Comment by rossihwang** [comment]
我粗略比较了下/sys/firmware/fdt和/proc/device-tree偏移出来的dts基本是一样的。不过论坛的dtb看起来使用rock96的改的？

**Comment by lanseyujie** [comment]
> 我粗略比较了下/sys/firmware/fdt和/proc/device-tree偏移出来的dts基本是一样的。不过论坛的dtb看起来使用rock96的改的？

是的
